version: 2

project_name: envset
before:
  hooks:
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      # - windows
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    ignore:
      - goos: darwin
        goarch: 386
      - goos: darwin
        goarch: arm
    main: "./cmd/envset/main.go"
    binary: "envset"
    ldflags:
      - -s -w
      - -X github.com/goliatone/go-envset/pkg/version.Tag=v{{.Version}}
      - -X github.com/goliatone/go-envset/pkg/version.Time={{.Date}}
      - -X github.com/goliatone/go-envset/pkg/version.User=goliatone
archives:
  - name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ if eq .Arch "amd64" }}x86_64{{ else if eq .Arch "386" }}i386{{ else }}{{ .Arch }}{{ end }}{{ with .Arm }}v{{ . }}{{ end }}'
checksum:
  name_template: "checksums.txt"
snapshot:
  version_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^Update README"
      - "merge fix"
brews:
  - name: envset
    repository:
      owner: goliatone
      name: homebrew-tap
    description: run commands in an environment defined using a ini configuration file.
    homepage: https://github.com/goliatone/go-envset
    license: "MIT"
    test: |
      system "#{bin}/envset -V"
nfpms:
  - id: envset
    file_name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ if eq .Arch "amd64" }}x86_64{{ else if eq .Arch "386" }}i386{{ else }}{{ .Arch }}{{ end }}{{ with .Arm }}v{{ . }}{{ end }}'
    bindir: /usr/local/bin/
    maintainer: goliatone <envset@goliat.one>
    description: run commands in an environment defined using a ini configuration file.
    homepage: https://github.com/goliatone/go-envset
    license: "MIT"
    formats:
      - deb
      - rpm
