# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
project_name: envset
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod download
    # you may remove this if you don't need go generate
    # - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      # - windows
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    main: "./cmd/envset/main.go"
    binary: "envset"
    ldflags:
      - -s -w -X pkg/version.Tag={{.Version}} -X pkg/version.Time={{.Date}} -X pkg/version.User=goliatone
archives:
  - replacements:
      386: i386
      amd64: x86_64
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
brews:
  - name: envset
    tap:
      owner: goliatone
      name: homebrew-tap
    description: run commands in an environment defined using a ini configuration file.
    homepage: https://github.com/goliatone/go-envset
    license: "MIT"
    test: |
      system "#{bin}/envset -V"
