name: "Go Build Test And Release"

on:
  push:
    branches:
      - master
  pull_request:

permissions:
  contents: read

jobs:
  build:
    name: "Build - Test - Release"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    env:
      VERBOSE: 1
      GOFLAGS: -mod=readonly
      GOPROXY: https://proxy.golang.org

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - name: Run build
        run: ./taskfile ci:build

      - name: Check formatting
        run: ./taskfile go:fmt:check

      - name: Run test
        run: ./taskfile ci:test

      - name: Run lint
        run: ./taskfile go:lint

      - name: Run clean
        run: ./taskfile ci:clean

      - name: Run release
        uses: goreleaser/goreleaser-action@v7
        with:
          version: "~> v2"
          args: release --snapshot --clean
