name: Release envset
on:
  push:
    tags:
      - v*.*.*
jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Unshallow Fetch
        run: git fetch --prune --unshallow
      - uses: actions/setup-go@v2
        with:
          go-version: "^1.13.0"
      - name: Release via goreleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          args: release
        env:
          GITHUB_TOKEN: ${{ secrets.GO_RELEASER_HOMEBREW_TAP }}
      - name: "Create latest tag"
        uses: EndBug/latest-tag@latest
        with:
          description: "lgr latest release"
